export const FETCH_CLIENT_DETAIL_REQUEST = 'FETCH_CLIENT_DETAIL_REQUEST';
export const FETCH_CLIENT_DETAIL_SUCCESS = 'FETCH_CLIENT_DETAIL_SUCCESS';
export const FETCH_CLIENT_DETAIL_FAIL = 'FETCH_CLIENT_DETAIL_FAIL';